import { diceRoller } from './dices.js'
import * as stats from './statCounter.js'
import {agregarAlDom} from './modificadorDom.js'
import * as creacionJSON from './creacionJSON.js'
import { main } from './three.js'
import  {dataDesdeFetch} from './fetch.js'